# WRAPPER MODULE airnvim
# ------------------------------------------------
inputs:
{
  lib,
  wlib,
  pkgs,
  config,
  options,
  ...
}:
let
  cfg = config.settings;
in
{
  imports = [ wlib.wrapperModules.neovim ];

  # OPTIONS
  # ------------------------------------------------
  options = {
    settings = {
      # --- Optional plugin groups ---
      ai = {
        enable = lib.mkEnableOption "AI chat (CodeCompanion)";
        adapter = lib.mkOption {
          type = lib.types.str;
          default = "copilot";
          example = "anthropic";
          description = ''
            CodeCompanion adapter used for chat, inline edits
            and commands. Adapters come in two kinds: HTTP ones
            authenticated with an API key in the environment
            (anthropic, openai, gemini, ollama, ...), and ACP
            ones reusing a CLI you already signed into with a
            subscription (copilot, claude_code, gemini_cli,
            codex, ...). No credential is stored in this repo.
          '';
        };
      };

      obsidian = {
        enable = lib.mkEnableOption "note taking with obsidian.nvim";
        vault = lib.mkOption {
          type = lib.types.str;
          default = "";
          example = "~/note";
          description = ''
            Path to the Obsidian vault. Without one the plugin
            stays out of the build, so it cannot create folders
            in whatever directory you happen to open the editor
            from.
          '';
        };
      };

      # --- Languages outside the daily profile ---
      # Off by default: they weigh hundreds of MB.
      langs = {
        python.enable = lib.mkEnableOption "Python LSP/linter (ruff)";

        # The two halves are independent on purpose. The servers
        # understand the code and cost ~225 MB, almost all of it
        # node; the formatter only rewrites the layout, weighs
        # ~64 MB and needs no node at all. Wanting tidy json or
        # css is not the same as wanting type checking.
        web = {
          enable = lib.mkEnableOption "web LSP (ts/js, html)";
          formatter.enable = lib.mkEnableOption "web formatter (biome: ts/js, html, css, json)";
        };
      };

      # --- Appearance and formatting ---
      # Off by default: cowsay is a perl script, so turning it on
      # adds the interpreter (~60 MB) and spends ~40 ms of
      # blocking io.popen at every startup. When off, alpha falls
      # back to the static header in lua/plugins/ui.lua.
      startup.cowsay = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = "alpha header generated by fortune+cowsay";
      };

      # image.nvim reaches imagemagick through luajit-magick, so
      # it is the plugin, not the CLI package, that carries the
      # weight: dropping only the package saves nothing.
      markdown.images.enable = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = ''
          Render images inside the buffer: image files opened
          directly, and markdown links under the cursor. Needs a
          terminal speaking the kitty graphics protocol (kitty,
          WezTerm, Ghostty, foot); elsewhere it does nothing.
          Turning it off saves about 137 MB.
        '';
      };

      markdown.line_length = lib.mkOption {
        type = lib.types.int;
        default = 75;
        description = ''
          Wrap column for markdown. Sets `textwidth` in .md
          buffers and rumdl's MD013 rule.
        '';
      };

      # rumdl rules are generated here instead of being left
      # to a project file: the LSP server reads a single
      # configuration file, so this way they apply anywhere.
      markdown.rules_file = lib.mkOption {
        type = lib.types.str;
        readOnly = true;
        default = toString (
          pkgs.writeText "rumdl.toml" ''
            # Generated by module.nix: do not edit by hand.

            [global]
            # MD024: headings repeating the same text
            # MD025: more than one level-1 heading per file
            # MD041: a file need not start with `#`
            disable = ["MD024", "MD025", "MD041"]

            [MD003]
            style = "atx"

            [MD004]
            style = "dash"

            [MD007]
            indent = 2
            style = "fixed"

            [MD013]
            line-length = ${toString cfg.markdown.line_length}
            # With strict = true the three exemptions below
            # are ignored
            strict = false
            # Headings, code and tables: no length limit
            headings = false
            code-blocks = false
            tables = false

            [MD035]
            style = "---"

            [MD046]
            style = "fenced"

            [MD048]
            style = "backtick"

            [MD049]
            style = "asterisk"

            [MD050]
            style = "asterisk"
          ''
        );
        description = "Path to the generated rumdl rules file";
      };

      # --- Look and feel ---
      # DankMaterialShell regenerates this from the wallpaper
      # through matugen, and every DMS integration reads it,
      # so it survives changes to their per-editor templates.
      # Empty means the default location under the XDG cache.
      theme.colors_file = lib.mkOption {
        type = lib.types.str;
        default = "";
        description = ''
          Path to the DankMaterialShell palette
          (dms-colors.json). When empty it is looked up at
          $XDG_CACHE_HOME/DankMaterialShell/dms-colors.json.
          If the file is missing the config falls back to the
          built-in palette in lua/core/palette.lua.
        '';
      };

      nerd_font.enable = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = ''
          Whether the terminal font is a Nerd Font. When off,
          file-type icons are left out: without the glyphs
          they render as empty boxes.
        '';
      };

      # --- External programs for `vim.ui.open` ---
      # Empty means "let the system decide": Neovim falls back
      # to xdg-open and the user's desktop associations. Set
      # only what you want to override.
      open =
        let
          mkOpener =
            description: example:
            lib.mkOption {
              type = lib.types.str;
              default = "";
              inherit example;
              description = "${description}. Empty: use xdg-open.";
            };
        in
        {
          browser = mkOpener "Program for http(s) links" "firefox";
          pdf = mkOpener "Program for PDF files" "zathura";
          image = mkOpener "Program for images" "imv";
          video = mkOpener "Program for videos" "mpv";

          # A directory needs both: xdg-open can only reach a
          # graphical file manager, never a terminal one.
          terminal = mkOpener "Terminal used to open a directory" "wezterm start --";
          filemanager = mkOpener "File manager run inside that terminal" "yazi";
        };

      # --- Spell checking ---
      # Off until `:SpellToggle` (or <leader>z). The
      # dictionaries are checked into spell/.
      spell = {
        enable = lib.mkOption {
          type = lib.types.bool;
          default = true;
          description = ''
            Allow `:SpellToggle`. Spell checking is never on
            automatically: this only decides whether the
            command can turn it on at all.
          '';
        };

        languages = lib.mkOption {
          type = lib.types.listOf lib.types.str;
          default = [
            "it"
            "en"
          ];
          example = [ "en" ];
          description = ''
            Dictionaries to check against. A word is accepted
            if any of them contains it, so several languages
            can be mixed in one document. Each entry needs the
            matching spell/<lang>.utf-8.spl file.
          '';
        };

        filetypes = lib.mkOption {
          type = lib.types.listOf lib.types.str;
          default = [ "markdown" ];
          description = "Filetypes where `:SpellToggle` works";
        };
      };

      render-backend = lib.mkOption {
        type = lib.types.enum [
          "ueberzug"
          "kitty"
        ];
        default = "kitty";
        description = ''
          Image backend. `kitty` also works on WezTerm, which
          implements the same protocol.
        '';
      };

      # Tells the lua side which top-level specs are enabled
      cats = lib.mkOption {
        readOnly = true;
        type = lib.types.attrsOf lib.types.bool;
        default = builtins.mapAttrs (_: v: v.enable) config.specs;
      };
    };

    nvim-lib = {
      neovimPlugins = lib.mkOption {
        readOnly = true;
        type = lib.types.attrsOf wlib.types.stringable;
        # Exposes plugins built from the inputs as
        # `config.nvim-lib.neovimPlugins.<name_without_prefix>`
        default = config.nvim-lib.pluginsFromPrefix "plugins-" inputs;
      };
      # Builds the plugins from the input set
      pluginsFromPrefix = lib.mkOption {
        type = lib.types.raw;
        readOnly = true;
        default =
          prefix: inputs:
          lib.pipe inputs [
            builtins.attrNames
            (builtins.filter (s: lib.hasPrefix prefix s))
            (map (
              input:
              let
                name = lib.removePrefix prefix input;
              in
              {
                inherit name;
                value = config.nvim-lib.mkPlugin name inputs.${input};
              }
            ))
            builtins.listToAttrs
          ];
      };
    };
  };

  # CONFIGURATION
  # ------------------------------------------------
  config = {
    # The binary stays `nvim`, with `nv` as its only alias
    binName = "nvim";

    # Providers for remote plugins written in other languages:
    # nothing here uses them and they drag in nodejs, python3
    # and ruby.
    hosts = {
      node.nvim-host.enable = false;
      python3.nvim-host.enable = false;
      ruby.nvim-host.enable = false;
    };

    settings = {
      config_directory = ./.; # Where the lua config lives
      aliases = [ "nv" ];
      ai.enable = lib.mkDefault false;
      obsidian.enable = lib.mkDefault true;
    };

    # SPECS: plugin and package groups
    # ------------------------------------------------
    specs = {
      # --- Plugin loader ---
      lze = [
        config.nvim-lib.neovimPlugins.lze
        {
          data = config.nvim-lib.neovimPlugins.lzextras;
          name = "lzextras";
        }
      ];

      # --- LSP, linters and formatters ---
      # Only the profile languages: nix, bash, lua, markdown.
      lsp = {
        data = with pkgs.vimPlugins; [
          nvim-lspconfig
        ];

        runtimePkgs =
          with pkgs;
          [
            # Nix
            nixd
            nixfmt
            statix
            deadnix
            # Bash
            shellcheck
            shfmt
            # Lua
            lua-language-server
            stylua
            selene
            # Markdown
            rumdl
          ]
          # Python on demand: ruff does lsp, lint and format
          ++ lib.optional cfg.langs.python.enable ruff
          # Web LSP on demand: pulls in nodejs
          ++ lib.optionals cfg.langs.web.enable [
            typescript-language-server
            vscode-langservers-extracted
          ]
          # Web formatter on demand, independent of the servers:
          # one rust binary covering ts/js, html, css and json
          ++ lib.optional cfg.langs.web.formatter.enable biome;
      };

      # --- General plugins ---
      general = {
        after = [ "lze" ];

        runtimePkgs =
          with pkgs;
          [
            # Search
            ripgrep
            fd
            # Git UI <leader>gg
            lazygit
          ]
          # Inline images (image.nvim, magick_cli processor)
          ++ lib.optional cfg.markdown.images.enable imagemagick
          # Dashboard header
          ++ lib.optionals cfg.startup.cowsay [
            fortune
            cowsay
          ]
          # Image backend alternative to kitty/wezterm
          ++ lib.optional (cfg.markdown.images.enable && cfg.render-backend == "ueberzug") ueberzugpp;

        # Child specs inherit the value of `lazy`
        lazy = true;

        data =
          with pkgs.vimPlugins;
          [
            {
              data = vim-sleuth;
              lazy = false;
            }

            # Theme. The palette comes from the desktop, see
            # lua/core/palette.lua; this only paints it on.
            base16-nvim

            # Interface
            lualine-nvim
            alpha-nvim
            fidget-nvim
            nvim-web-devicons
            nvim-colorizer-lua
            todo-comments-nvim

            # Editing
            nvim-surround
            nvim-autopairs
            nvim-spectre
            undotree
            oil-nvim
            lazydev-nvim
            actions-preview-nvim
            plenary-nvim

            # Git
            gitsigns-nvim
            lazygit-nvim
            diffview-nvim

            # Telescope
            telescope-nvim
            telescope-fzf-native-nvim
            telescope-ui-select-nvim

            # Completion
            nvim-cmp
            cmp_luasnip
            cmp-nvim-lsp
            cmp-path
            cmp-buffer
            cmp-cmdline
            luasnip
            friendly-snippets

            # Lint and formatting
            conform-nvim
            nvim-lint

            # Markdown
            render-markdown-nvim

            # Treesitter: only the grammars actually used
            nvim-treesitter-textobjects
            (nvim-treesitter.withPlugins (
              p: with p; [
                # Config and system
                bash
                nix
                lua
                luadoc
                vim
                vimdoc
                query
                # Markup and data
                markdown
                markdown_inline
                yaml
                toml
                json
                # Web
                html
                css
                scss
                javascript
                typescript
                tsx
                jsdoc
                java
                # Other languages
                python
                c
                cpp
                rust
                # Utilities
                regex
                comment
                diff
                gitcommit
                gitignore
                git_rebase
              ]
            ))
          ]
          # Inline images: the plugin drags imagemagick in
          ++ lib.optional cfg.markdown.images.enable image-nvim;
      };

      # --- Optional groups (feature flags) ---
      ai = {
        enable = cfg.ai.enable;
        lazy = true;
        data = with pkgs.vimPlugins; [
          codecompanion-nvim
        ];
      };

      # An explicit vault is required: without one the plugin
      # is not even included
      obsidian = {
        enable = cfg.obsidian.enable && cfg.obsidian.vault != "";
        lazy = true;
        data = with pkgs.vimPlugins; [
          obsidian-nvim
        ];
      };
    };

    # Adds the `runtimePkgs` field to every spec
    specMods = _: {
      options.runtimePkgs = options.runtimePkgs // {
        description = "Spec field for putting packages on the PATH";
      };
    };

    runtimePkgs = config.specCollect (acc: v: acc ++ (v.runtimePkgs or [ ])) [ ];
  };
}
