-- SHARED MARKDOWN RULES (rumdl)
--------------------------------------------------
-- The rules live in a file generated by module.nix. A file is
-- required: the LSP server ignores overrides passed on the
-- command line, while `configPath` works and applies outside
-- projects carrying their own .rumdl.toml.

local M = {}

-- Path to the rules file, nil outside the Nix wrapper --
function M.config_path()
	local path = nixInfo(nil, "settings", "markdown", "rules_file")
	if path and vim.fn.filereadable(path) == 1 then
		return path
	end
	return nil
end

-- Arguments for the command-line subcommands --
function M.args()
	local path = M.config_path()
	if path then
		return { "--config", path }
	end

	-- Outside the wrapper, fall back to inline overrides
	local len = nixInfo(75, "settings", "markdown", "line_length")
	return {
		"--config",
		"MD013.line-length = " .. tostring(len),
		"--config",
		"MD013.strict = false",
		"--config",
		"MD013.headings = false",
		"--config",
		"MD013.code-blocks = false",
		"--config",
		"MD013.tables = false",
		"--config",
		'global.disable = ["MD024", "MD025", "MD041"]',
	}
end

return M
